<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">


 <xacro:arg name="is_ignition" default="true"/>


 <!-- Include Gazebo Parameters -->
  <xacro:include filename="$(find rabo_description)/urdf/rabo_gazebo.xacro" />

 
 <!--ROS2 Control -->
  <xacro:include filename="$(find rabo_description)/urdf/rabo_ros2_control.xacro" />


  
  <!-- Basic robot dimensions -->
  <xacro:property name="base_length" value="0.17" />
  <xacro:property name="base_width" value="0.15" />
  <xacro:property name="base_height" value="0.07" />
  <xacro:property name="wheel_radius" value="0.033" />
  <xacro:property name="wheel_length" value="0.025" />

  <!-- -->
  <xacro:macro name="sphere_inertia" params="m r xyz rpy">
    <inertial>
        <origin xyz="${xyz}" rpy="${rpy}" />
        <mass value="${m}" />
        <inertia ixx="${(2/5) * m * r * r}" ixy="0" ixz="0"
                  iyy="${(2/5) * m * r * r}" iyz="0"
                  izz="${(2/5) * m * r * r}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="m l w h xyz rpy">
    <inertial>
        <origin xyz="${xyz}" rpy="${rpy}" />
        <mass value="${m}" />
        <inertia ixx="${(m/12) * (h*h + l*l)}" ixy="0" ixz="0"
                  iyy="${(m/12) * (w*w + l*l)}" iyz="0"
                  izz="${(m/12) * (w*w + h*h)}" />
    </inertial>
  </xacro:macro>


  <!-- Base footprint -->
  <link name="base_footprint" />

  <!-- Main base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </collision>
    <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                       xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
  </link>

  <!-- Base joint connects footprint to base_link -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Caster wheel (rear center) -->
  <link name="caster_wheel_link">
    <visual>
      <geometry>
        <sphere radius="${wheel_radius / 2.0}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <material name="grey" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius / 2.0}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </collision>
    <xacro:sphere_inertia m="0.5" r="${wheel_radius}" xyz="0 0 0" rpy="0 0 0" />
  </link>

  <joint name="base_caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="caster_wheel_link" />
    <origin xyz="${-base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
  </joint>

  <!-- Left wheel -->
  <link name="wheel_left_link">
    <inertial>
      <origin xyz="0 0.014 0" rpy="0 0 0" />
      <mass value="0.053" />
      <inertia ixx="1.88e-5" ixy="0" ixz="0" iyy="3.12e-5" iyz="0" izz="1.88e-5" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="-1.57 0 0" />
      <geometry>
        <mesh filename="package://rabo_description/meshes/wheel_left_link.STL" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 0.015 0" rpy="-1.57 0 0" />
      <geometry>
        <sphere radius="0.033" />
      </geometry>
    </collision>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <origin xyz="${base_length / 4.0} ${(base_width) / 2.0} 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_left_link" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Right wheel -->
  <link name="wheel_right_link">
    <inertial>
      <origin xyz="0 -0.014 0" rpy="0 0 0" />
      <mass value="0.053" />
      <inertia ixx="1.88e-5" ixy="0" ixz="0" iyy="3.12e-5" iyz="0" izz="1.88e-5" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0" />
      <geometry>
        <mesh filename="package://rabo_description/meshes/wheel_right_link.STL" />
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <origin xyz="0 -0.015 0" rpy="1.57 0 0" />
      <geometry>
        <sphere radius="0.033" />
      </geometry>
    </collision>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <origin xyz="${base_length / 4.0} ${-(base_width ) / 2.0} 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="wheel_right_link" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Laser scanner -->
  <link name="laser_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="0.073" />
      <inertia ixx="2e-5" ixy="0" ixz="0" iyy="2.4e-5" iyz="0" izz="4.1e-5" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://rabo_description/meshes/laser_link.STL" />
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://rabo_description/meshes/laser_link.STL" />
      </geometry>
    </collision>
  </link>

  <joint name="laser_joint" type="fixed">
    <origin xyz="-0.0050526 -0.0023221 0.1" rpy="0 0 3.14" />
    <parent link="base_link" />
    <child link="laser_link" />
  </joint>

  <!-- LED Left -->
  <link name="LedLeft_frame">
    <visual>
      <geometry>
        <cylinder radius="0.01" length="0.005"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.01" length="0.005"/>
      </geometry>
    </collision>
  </link>

  <joint name="LedLeft_joint" type="fixed">
    <parent link="base_link"/>
    <child link="LedLeft_frame"/>
    <origin xyz="${base_length/2.0} 0.04 0.04" rpy="0 1.57 0"/>
  </joint>

  <!-- LED Right -->
  <link name="LedRight_frame">
    <visual>
      <geometry>
        <cylinder radius="0.01" length="0.005"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.01" length="0.005"/>
      </geometry>
    </collision>
  </link>

  <joint name="LedRight_joint" type="fixed">
    <parent link="base_link"/>
    <child link="LedRight_frame"/>
    <origin xyz="${base_length/ 2.0} -0.04 0.04" rpy="0 1.57 0"/>
  </joint>

  <!-- Front Ultrasonic Sensor -->
  <link name="ultrasonic_frameF">
    <visual>
      <geometry>
        <cylinder radius="0.01" length="0.005"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.01" length="0.005"/>
      </geometry>
    </collision>
  </link>

  <joint name="ultrasonic_jointF" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_frameF"/>
    <origin xyz="${base_length/ 2.0} 0 0.03" rpy="0 0 0"/>
  </joint>

  <material name="blue">
        <color rgba="0 0 1 1" />
  </material>

  <material name="white">
      <color rgba="1 1 1 1" />
  </material>

  <!-- Colors -->

  <material name="grey">
      <color rgba="0.5 0.5 0.5 1" />
  </material>

  <material name="black">
      <color rgba="0.0 0.0 0.0 1" />
  </material>


  <material name="silver">
      <color rgba="0.79 0.82 0.93 1"/>
  </material>

  <material name="dark_grey">
      <color rgba="0.3 0.3 0.3 1"/>
  </material>

  <material name="yellow">
      <color rgba="1 1 0 1"/>
  </material>


  <link name="imu_link">
    <inertial>
      <origin xyz="-0.00552433659106688 0.000168210391520346 0.000514000497342681" rpy="0 0 0" />
      <mass value="0.000528415362211671" />
      <inertia ixx="1.46176048428261E-08" ixy="1.40015117949421E-10" ixz="-1.99633872937403E-12"
               iyy="8.59662482954888E-09" iyz="7.52375112767959E-12"
               izz="2.30279421279312E-08" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://rabo_description/meshes/imu_link.STL" />
      </geometry>
      <material name="">
        <color rgba="0.792156862745098 0.819607843137255 0.933333333333333 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://rabo_description/meshes/imu_link.STL" />
      </geometry>
    </collision>
  </link>
  
  <joint name="imu_joint" type="fixed">
    <origin xyz="0 0 0.035" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="imu_link" />
    <axis xyz="0 0 0" />
  </joint>
  


</robot>
